### ISSUE TITLE
Android 앱 출시 준비

### ISSUE THREAD

**Issue by jja08111** [Foundy-LLC/p_lyric#76]
### TODO
- [x] #77 
- [x] 앱 서명하기
- [x] Proguard 사용
- [x] 앱 매니페스트 검토하기
- [x] 빌드 구성 검토하기
- [x] release 앱 번들 빌드하기
- [x] Google Play 스토어에 APK 출시하기

### 참고 
https://flutter-ko.dev/docs/deployment/android

**Comment by alpha-src** [comment]
준비 완료!
